### ISSUE TITLE
Movements not being displayed correctly 

### ISSUE THREAD

**Issue by MoonbaseRey** [BlauhausTechnology/MoonbaseIssues#14]
Launched an attack on Boris. timer immediately went to 00:00 and line is not moving.
![ss3](https://user-images.githubusercontent.com/47919655/53302361-17e1bb80-3866-11e9-8caa-e8bf0cb8e970.jpg)

![sws4](https://user-images.githubusercontent.com/47919655/53302370-2def7c00-3866-11e9-9866-378242f012e7.jpg)

**Comment by MoonbaseRey** [comment]
It is only once the raid returns to base that the line and timer clears

**Comment by freever** [comment]
I've had this one too a few times. Mostly it goes away if I just resync. Once however it only went away when the attack came back. 

This is really hard to diagnose because it's intermittent and doesn't give off any errors or any clues. Let's keep this issue open and log as many clues as we can whenever we find them

**Comment by freever** [comment]
There's only one way I can currently imagine this happening, and I've plugged that hole in 0.13.4. @MoonbaseRey  Please let me know if you still get this issue after updating
