### ISSUE TITLE
Sea of Epsilon - Activity after Pause

### ISSUE THREAD

**Issue by MoonbaseRey** [BlauhausTechnology/MoonbaseIssues#22]
After the pause last night a number of new bases have been popping up around me and my rank has changed. 'Skollie' popped up less than an hour ago and my rank dropped by 1. From my side, I can't do anything, the entire game is paused

**Comment by Thaldoras** [comment]
Depends on how the pause was implemented. Maybe there are some things that aren't disabled on the server side.

**Comment by freever** [comment]
When the game is paused, none of the timers run and you cannot initiate new structure upgrades, movements, or unit construction. You can chat, and you can probably even do alliance stuff. You can browse the game. 

I see no reason why we can't allow new players to join during a pause... in fact I think in future, servers will actually launch in a paused state so that players can join in an orderly fashion and be ready to start upgrading and doing their thing as soon as the server unpauses. A lot of the problems that happen with servers happen in the first minute when everyone joins at the same time... I think this will alleviate some of that pressure and also allow players to ease in to a sort of check in lounge or lobby before the game actually starts. When we have server-wide chat it could be cool.
