### ISSUE TITLE
Alliance Scoreboard Displays Wrong Score

### ISSUE THREAD

**Issue by Thaldoras** [BlauhausTechnology/MoonbaseIssues#25]
The alliance scoreboard doesn't update its score when a member leaves. This causes alliances with lower display scores to be higher rank than one who has had a member leave.

**Comment by Thaldoras** [comment]
Okay I am starting to think this was fixed and alliances now keep the score from members who left.

**Comment by freever** [comment]
The expected behaviour is as follows: Clan score is an accumulation of all scores earned by players while they were a member of the Clan. So it includes scores earned by all current AND former members while they were part of the clan, and excludes all scores earned by current and former members while they weren't part of the Clan. 

@Thaldoras  If this is the behaviour you are seeing, we can close this.

**Comment by Thaldoras** [comment]
That is the behavior. This can be closed.
