### ISSUE TITLE
Insufficient Resources Error

### ISSUE THREAD

**Issue by MoonbaseRey** [BlauhausTechnology/MoonbaseIssues#28]
Insufficient resource error even though there are sufficient resources

![screenshot_20190307-161922](https://user-images.githubusercontent.com/47919655/53963335-c5ba5900-40f5-11e9-84ef-1c6beb7e23e3.png)

![screenshot_20190307-161922](https://user-images.githubusercontent.com/47919655/53963344-ca7f0d00-40f5-11e9-861e-24a0a3277dd0.png)

**Comment by MoonbaseRey** [comment]
![screenshot_20190307-161929](https://user-images.githubusercontent.com/47919655/53963413-f0a4ad00-40f5-11e9-9450-ba55232eae15.png)

**Comment by freever** [comment]
In this case the problem seems to be that the device and the server disagree about the quantity of helium you have. 

![image](https://user-images.githubusercontent.com/2269624/53964866-c99baa80-40f8-11e9-952a-d05d9539addf.png)

The other resources are off by a little bit which I would expect due to the challenges of synchronizing device and server times... but the helium suggests some deeper failure, like maybe units moving from one base to another failed to update the device so consumption was out of whack.

**Comment by freever** [comment]
I think this is bound to happen from time to time, so what I've done is made it so whenever the error occurs, the server will update the client with accurate resources so *hopefully* the error will then correct itself immediately. Let's monitor and see....
